### ISSUE TITLE
Playlist tracks

### ISSUE THREAD

**Issue by hispeedsurfer** [Lukayne/spotifyshuffler#1]
Hello,

This project is very interesting. I’m new to swift and Spotify programming. 
My concern is whether it is possible with a little modification to select a track in the list and play it and the other tracks one after the other. The current track should be highlighted.

**Comment by Lukayne** [comment]
Hi, 

That would pretty much defeat the entire purpose of the applications main goal. 

But to answer your question: Yes, you could implement that feature. I would advise you to look into the following API: https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback. You've already got the URI for the song (`trackObject`). But Spotify needs to know what songs they should be playing thereafter thus you need to add context.

**Comment by hispeedsurfer** [comment]
@Lukayne thank you for your response. I think I only know how to do it for my purposes.

**Comment by hispeedsurfer** [comment]
One question, can I integrate your repository to use your models etc. In one of my repositories because you have no LICENSE.txt on repository. It’s only for private/non-commercial use.

**Comment by Lukayne** [comment]
Go ahead, feel free to use the code however you wish.
